use axum::extract::DefaultBodyLimit;
use axum::routing::{delete, get, post};
use axum::Router;

use super::ATTACHMENT_REQUEST_MAX_BYTES;
use crate::handlers::{agents, remote_files, shares, swarm};
use crate::state::AppState;

pub(super) fn agent_routes() -> Router<AppState> {
    Router::new()
        .route(
            "/api/agents",
            post(agents::create_agent).get(agents::list_agents),
        )
        .route(
            "/api/agents/:agent_id",
            get(agents::get_agent)
                .put(agents::update_agent)
                .delete(agents::delete_agent),
        )
        .route(
            "/api/agents/:agent_id/clone",
            post(agents::clone_agent),
        )
        .route(
            "/api/agents/:agent_id/projects",
            get(agents::list_agent_project_bindings),
        )
        .route(
            "/api/agents/:agent_id/projects/:project_agent_id",
            delete(agents::remove_agent_project_binding),
        )
        .route(
            "/api/agents/:agent_id/delegate_task",
            post(agents::delegate_agent_task),
        )
        .route(
            "/api/agents/:agent_id/state_snapshot",
            get(agents::get_agent_state_snapshot),
        )
        .route(
            "/api/agents/:agent_id/self-improvement",
            get(agents::get_self_improvement_config).put(agents::update_self_improvement_config),
        )
        .route(
            "/api/agents/:agent_id/improvements",
            get(agents::list_improvement_proposals),
        )
        .route(
            "/api/agents/:agent_id/improvements/propose",
            post(agents::propose_improvement),
        )
        .route(
            "/api/agents/:agent_id/improvements/review",
            post(agents::run_learning_review),
        )
        .route(
            "/api/agents/:agent_id/improvements/:proposal_id/apply",
            post(agents::apply_improvement_proposal),
        )
        .route(
            "/api/agents/:agent_id/improvements/:proposal_id/reject",
            post(agents::reject_improvement_proposal),
        )
        .route(
            "/api/agents/:agent_id/remote_agent/state",
            get(swarm::get_remote_agent_state),
        )
        .route(
            "/api/agents/:agent_id/remote_agent/logs",
            get(swarm::get_remote_agent_logs),
        )
        .route(
            "/api/agents/:agent_id/remote_agent/files",
            post(remote_files::list_remote_directory),
        )
        .route(
            "/api/agents/:agent_id/remote_agent/read-file",
            post(remote_files::read_remote_file),
        )
        .route(
            "/api/agents/:agent_id/remote_agent/recover",
            post(swarm::recover_remote_agent),
        )
        .route(
            "/api/agents/:agent_id/remote_agent/:action",
            post(swarm::remote_agent_lifecycle),
        )
        .route(
            "/api/agents/:agent_id/events",
            get(agents::list_agent_events),
        )
        .route(
            "/api/agents/:agent_id/events/paginated",
            get(agents::list_agent_events_paginated),
        )
        .route(
            "/api/agents/:agent_id/sessions/:session_id/events",
            get(agents::list_agent_session_events),
        )
        .route(
            "/api/agents/:agent_id/sessions/:session_id/aside",
            post(agents::ask_agent_session_aside),
        )
        .route(
            "/api/agents/:agent_id/sessions/:session_id/events/paginated",
            get(agents::list_agent_session_events_paginated),
        )
        .route(
            "/api/agents/:agent_id/runtime/test",
            post(agents::test_agent_runtime),
        )
        .route(
            "/api/agents/:agent_id/events/stream",
            // Chat input bar inlines base64 image attachments in the
            // request body; raise above Axum's default 2 MiB cap so a
            // pasted screenshot doesn't surface as `Failed to fetch`.
            post(agents::send_agent_event_stream)
                .layer(DefaultBodyLimit::max(ATTACHMENT_REQUEST_MAX_BYTES)),
        )
        .route(
            "/api/agents/:agent_id/public-chat/import",
            post(agents::import_public_chat_session),
        )
        .route(
            "/api/agents/:agent_id/reset-session",
            post(agents::reset_agent_session),
        )
        .route(
            "/api/agents/:agent_id/cancel-turn",
            post(agents::cancel_agent_turn),
        )
        .route(
            "/api/agents/:agent_id/context-usage",
            get(agents::get_agent_context_usage),
        )
        .route(
            "/api/agents/:agent_id/context-contents",
            get(agents::get_agent_context_contents),
        )
        .route(
            "/api/agents/:agent_id/installed-tools",
            get(agents::get_installed_tools_diagnostic),
        )
        .route(
            "/api/projects/:project_id/agents",
            post(agents::create_agent_instance).get(agents::list_agent_instances),
        )
        .route(
            "/api/projects/:project_id/agents/:agent_instance_id",
            get(agents::get_agent_instance)
                .put(agents::update_agent_instance)
                .delete(agents::delete_agent_instance),
        )
        .route(
            "/api/projects/:project_id/agents/:agent_instance_id/events",
            get(agents::list_events),
        )
        .route(
            "/api/projects/:project_id/agents/:agent_instance_id/events/stream",
            // Same attachment-body rationale as the standalone-agent
            // events stream above.
            post(agents::send_event_stream)
                .layer(DefaultBodyLimit::max(ATTACHMENT_REQUEST_MAX_BYTES)),
        )
        .route(
            "/api/projects/:project_id/agents/:agent_instance_id/reset-session",
            post(agents::reset_instance_session),
        )
        .route(
            "/api/projects/:project_id/agents/:agent_instance_id/cancel-turn",
            post(agents::cancel_instance_turn),
        )
        .route(
            "/api/projects/:project_id/agents/:agent_instance_id/context-usage",
            get(agents::get_instance_context_usage),
        )
        .route(
            "/api/projects/:project_id/agents/:agent_instance_id/context-contents",
            get(agents::get_instance_context_contents),
        )
        .route(
            "/api/projects/:project_id/agents/:agent_instance_id/sessions",
            get(agents::list_sessions),
        )
        .route(
            "/api/projects/:project_id/agents/:agent_instance_id/sessions/:session_id",
            get(agents::get_session).delete(agents::delete_session),
        )
        .route(
            "/api/projects/:project_id/agents/:agent_instance_id/sessions/:session_id/branch",
            post(agents::branch_session),
        )
        .route(
            "/api/projects/:project_id/agents/:agent_instance_id/sessions/:session_id/safe-workspace",
            get(agents::get_safe_workspace_status),
        )
        .route(
            "/api/projects/:project_id/agents/:agent_instance_id/safe-workspace-eligibility",
            get(agents::get_safe_workspace_eligibility),
        )
        .route(
            "/api/projects/:project_id/agents/:agent_instance_id/sessions/:session_id/safe-workspace/apply",
            post(agents::apply_safe_workspace_to_project),
        )
        .route(
            "/api/projects/:project_id/agents/:agent_instance_id/sessions/:session_id/safe-workspace/checkpoints/:checkpoint_id/diff",
            get(agents::get_safe_workspace_checkpoint_diff),
        )
        .route(
            "/api/projects/:project_id/agents/:agent_instance_id/sessions/:session_id/safe-workspace/checkpoints/:checkpoint_id/restore",
            post(agents::restore_safe_workspace_checkpoint),
        )
        .route(
            "/api/projects/:project_id/agents/:agent_instance_id/sessions/:session_id/tasks",
            get(agents::list_session_tasks),
        )
        .route(
            "/api/projects/:project_id/agents/:agent_instance_id/sessions/:session_id/events",
            get(agents::list_session_events),
        )
        .route(
            "/api/projects/:project_id/agents/:agent_instance_id/sessions/:session_id/aside",
            post(agents::ask_instance_session_aside),
        )
        .route(
            "/api/projects/:project_id/agents/:agent_instance_id/sessions/:session_id/events/paginated",
            get(agents::list_session_events_paginated),
        )
        .route(
            "/api/projects/:project_id/agents/:agent_instance_id/sessions/:session_id/share",
            post(shares::create_session_share),
        )
        .route(
            "/api/projects/:project_id/agents/:agent_instance_id/sessions/:session_id/subagents",
            get(agents::list_session_subagents),
        )
        .route(
            "/api/projects/:project_id/agents/:agent_instance_id/sessions/:session_id/summarize",
            post(agents::summarize_session),
        )
        .route(
            "/api/projects/:project_id/sessions",
            get(agents::list_project_sessions),
        )
        .route("/api/me/sessions", get(agents::list_my_sessions))
        .route(
            "/api/me/sessions/search",
            get(agents::search_my_session_history),
        )
}
