export const TOOL_LABELS: Record<string, string> = {
  list_specs: "List specs",
  get_spec: "Get spec",
  create_spec: "Create spec",
  update_spec: "Update spec",
  delete_spec: "Delete spec",
  list_tasks: "List tasks",
  create_task: "Create task",
  update_task: "Update task",
  delete_task: "Delete task",
  transition_task: "Transition task",
  run_task: "Run task",
  get_project: "Get project",
  update_project: "Update project",
  start_dev_loop: "Start dev loop",
  pause_dev_loop: "Pause dev loop",
  stop_dev_loop: "Stop dev loop",
  read_file: "Read file",
  write_file: "Write file",
  edit_file: "Edit file",
  delete_file: "Delete file",
  list_files: "List files",
  find_files: "Find files",
  search_code: "Search code",
  run_command: "Run command",
  stat_file: "File info",
  submit_plan: "Submit plan",
  task_done: "Task complete",
  get_task_context: "Load context",
  git_commit: "Commit code",
  git_push: "Push code",
  completion_gate_rejected: "Completion gate rejected",
  create_project: "Create project",
  list_projects: "List projects",
  import_project: "Import project",
  delete_project: "Delete project",
  archive_project: "Archive project",
  get_project_stats: "Project stats",
  list_agents: "List agents",
  get_agent: "Get agent",
  create_agent: "Create agent",
  update_agent: "Update agent",
  delete_agent: "Delete agent",
  assign_agent_to_project: "Assign agent",
  list_agent_instances: "List agent instances",
  update_agent_instance: "Update agent instance",
  delete_agent_instance: "Remove agent",
  remote_agent_action: "Remote agent action",
  get_loop_status: "Loop status",
  send_to_agent: "Send to agent",
  get_fleet_status: "Fleet status",
  get_progress_report: "Progress report",
  get_project_cost: "Project cost",
  get_credit_balance: "Credit balance",
  get_transactions: "Transactions",
  get_billing_account: "Billing account",
  purchase_credits: "Purchase credits",
  generate_specs: "Generate specs",
  generate_specs_summary: "Specs summary",
  list_tasks_by_spec: "Tasks by spec",
  extract_tasks: "Extract tasks",
  retry_task: "Retry task",
  get_task_output: "Task output",
  list_orgs: "List organizations",
  create_org: "Create organization",
  get_org: "Get organization",
  update_org: "Update organization",
  list_members: "List members",
  update_member_role: "Update member role",
  remove_member: "Remove member",
  manage_invites: "Manage invites",
  list_feed: "Activity feed",
  create_post: "Create post",
  get_post: "Get post",
  add_comment: "Add comment",
  delete_comment: "Delete comment",
  follow_profile: "Follow",
  unfollow_profile: "Unfollow",
  list_follows: "Following",
  get_leaderboard: "Leaderboard",
  get_usage_stats: "Usage stats",
  list_sessions: "List sessions",
  list_log_entries: "Log entries",
  browse_files: "Browse files",
  get_environment_info: "Environment info",
  get_remote_agent_state: "Remote agent state",
  generate_image: "Generate image",
  generate_3d_model: "Generate 3D model",
  generate_video: "Generate video",
  get_3d_status: "3D generation status",
  load_domain_tools: "Load tools",
};

export const TOOL_PHASE_LABELS: Record<string, string> = {
  read_file: "Reading files...",
  write_file: "Writing code...",
  edit_file: "Editing code...",
  list_files: "Browsing the project...",
  find_files: "Searching for files...",
  search_code: "Searching code...",
  run_command: "Running command...",
  stat_file: "Checking file info...",
  delete_file: "Cleaning up...",
  create_spec: "Drafting specs...",
  update_spec: "Drafting specs...",
  list_specs: "Reviewing specs...",
  get_spec: "Reviewing specs...",
  delete_spec: "Reviewing specs...",
  create_task: "Organizing tasks...",
  update_task: "Organizing tasks...",
  list_tasks: "Managing tasks...",
  delete_task: "Managing tasks...",
  transition_task: "Managing tasks...",
  run_task: "Running a task...",
  start_dev_loop: "Firing up the dev loop...",
  pause_dev_loop: "Managing the dev loop...",
  stop_dev_loop: "Managing the dev loop...",
  get_project: "Checking the project...",
  update_project: "Checking the project...",
  submit_plan: "Submitting plan...",
  task_done: "Finishing up...",
  get_task_context: "Loading context...",
  git_commit: "Committing code...",
  git_push: "Pushing code...",
  create_project: "Creating project...",
  list_projects: "Listing projects...",
  delete_project: "Deleting project...",
  assign_agent_to_project: "Assigning agent...",
  get_fleet_status: "Checking fleet status...",
  get_progress_report: "Generating progress report...",
  get_credit_balance: "Checking credits...",
  generate_specs: "Generating specs...",
  extract_tasks: "Extracting tasks...",
  generate_image: "Generating image...",
  generate_3d_model: "Generating 3D model...",
  generate_video: "Generating video...",
  load_domain_tools: "Loading additional tools...",
  send_to_agent: "Sending message to agent...",
};

export const FILE_OPS = new Set(["write_file", "edit_file", "read_file", "delete_file"]);
export const COMMAND_OPS = new Set(["run_command"]);
