// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Free-form agent persona surfaced into the assembled system prompt's
 * `<agent_identity>` section.
 *
 * Every field is best-effort prose: aura-os reads it off the
 * `agent_instance` row, the harness splices it into the prompt
 * verbatim. Empty / blank fields are dropped at render time so an
 * uninitialised wire payload produces no model-facing bytes.
 */
export type AgentPersona = { name: string, role: string, personality: string, };
