// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentPersona } from "./AgentPersona";

/**
 * "Who is this agent" bundle.
 */
export type AgentIdentity = { 
/**
 * Stable template agent UUID — the row in the `agents` table.
 */
template_id: string | null, 
/**
 * Partitioned harness agent id, one of:
 * - `{template}::default`        (bare agent, no instance/session axis)
 * - `{template}::{instance}`     (per-instance partition)
 * - `{template}::{instance}::{session}` (per-(instance, session) partition)
 */
partition_id: string | null, 
/**
 * Persona fields rendered into the `<agent_identity>` section
 * of the assembled system prompt.
 */
persona: AgentPersona | null, 
/**
 * Operator-curated skill names rendered as `<agent_skills>` in
 * the assembled system prompt.
 */
skills: Array<string>, 
/**
 * Operator-authored system prompt (the "system prompt"
 * textarea on the agent template). Rendered as
 * `<agent_system_prompt>`.
 */
system_prompt: string | null, };
