// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstalledIntegration } from "./InstalledIntegration";
import type { InstalledTool } from "./InstalledTool";
import type { IntentClassifierSpec } from "./IntentClassifierSpec";

/**
 * "What tools / integrations / intent classifier the agent can use."
 */
export type AgentCapabilities = { 
/**
 * Installed tools registered for this run.
 */
installed_tools: Array<InstalledTool>, 
/**
 * Installed integrations authorized for this run.
 */
installed_integrations: Array<InstalledIntegration>, 
/**
 * Optional keyword-driven intent classifier spec.
 */
intent_classifier: IntentClassifierSpec | null, };
