// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Typed project descriptor surfaced into the chat-path system prompt's
 * `<project_context>` section.
 *
 * Every field is best-effort prose: aura-os reads it off the
 * `projects` row, the harness splices it into the prompt verbatim.
 * Empty / blank fields are dropped at render time so an
 * uninitialised wire payload produces no stray `description: ` /
 * `build_command: ` lines.
 */
export type ChatProjectInfoWire = { 
/**
 * Stable project UUID, surfaced as `project_id` in the
 * `<project_context>` block.
 */
id: string, 
/**
 * Operator-authored project name.
 */
name: string, 
/**
 * Operator-authored project description. Blank ⇒ the renderer
 * drops the `description:` line entirely.
 */
description: string, 
/**
 * Absolute workspace root on the harness host. Surfaced as the
 * `folder:` line of `<project_context>` and used by
 * `agents_md_from_workspace()` to locate `AGENTS.md`.
 */
workspace_root: string, 
/**
 * Configured build command (e.g. `cargo build`). Blank ⇒ the
 * renderer drops `build_command:`.
 */
build_command: string, 
/**
 * Configured test command (e.g. `cargo test`). Blank ⇒ the
 * renderer drops `test_command:`.
 */
test_command: string, };
