// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One rendered entry inside a context bucket (e.g. a single tool
 * definition or skill). Named `ContextSegment` rather than `Item` per
 * the TS naming rule, kept identical across Rust + TS for the binding.
 */
export type ContextSegment = { label: string, text: string, tokens: bigint, };
