// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-bucket token estimates for the current session context, computed
 * using the same `chars / CHARS_PER_TOKEN` heuristic as
 * [`SessionUsage::estimated_context_tokens`]. The buckets approximate
 * what the model actually receives on the next turn:
 *
 * - `system_prompt_tokens` — the rendered system prompt.
 * - `tools_tokens` — serialized tool definitions (name + description +
 *   JSON schema for each tool the request would carry).
 * - `skills_tokens` — installed skill metadata (name + description).
 * - `mcp_tokens` — reserved for MCP server context once aura-harness
 *   gains MCP support; today this is always `0`.
 * - `subagents_tokens` — registered subagent kind specs.
 * - `conversation_tokens` — the live message transcript including
 *   tool results and assistant turns. This is the same number as
 *   `estimated_context_tokens` minus the static buckets above.
 */
export type ContextBreakdown = { system_prompt_tokens: bigint, tools_tokens: bigint, skills_tokens: bigint, mcp_tokens: bigint, subagents_tokens: bigint, conversation_tokens: bigint, cache_read_tokens?: bigint, cache_creation_tokens?: bigint, };
