// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextSegment } from "./ContextSegment";

/**
 * Rendered text the harness counted for each static context bucket.
 * All fields optional/defaulted so older harness builds decode to an
 * empty value rather than failing (mirrors [`ContextBreakdown`]).
 */
export type ContextContents = { system_prompt: string | null, tools: Array<ContextSegment>, skills: Array<ContextSegment>, subagents: Array<ContextSegment>, mcp: Array<ContextSegment>, };
