// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How an AURA Council combines its members' answers once every member
 * has completed. Selected by the user before the run; applied by the
 * synthesizer (`members[0]`) in the final turn the UI renders below the
 * council panel.
 *
 * Wire format is snake_case (`synthesize` / `contrast` / `side_by_side`).
 * `#[serde(default)]` on the [`RuntimeRequestType::Council`] field folds
 * older clients that omit it into [`Self::Synthesize`], the prior
 * behavior.
 */
export type CouncilMechanism = "synthesize" | "contrast" | "side_by_side";
