// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-file diff metadata that runs alongside the path lists in
 * [`FilesChanged`]. Optional and additive: senders that don't compute
 * line counts (older harnesses, write/delete tool paths) simply omit
 * the entry, and consumers must treat "no entry for path" / "0 / 0"
 * as "unknown", not "no change".
 */
export type FileDiff = { path: string, lines_added: number, lines_removed: number, };
