// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileDiff } from "./FileDiff";

/**
 * Summary of file mutations during a turn.
 *
 * `diffs` is a parallel list of per-path line-count metadata. It lives
 * alongside `created` / `modified` / `deleted` (rather than replacing
 * them) so older clients that only know about the path lists keep
 * working untouched. The serde default + skip_if_empty pair keeps the
 * wire format byte-identical when no diffs are computed, preserving
 * JSON-shape compatibility with any pinned schemas.
 */
export type FilesChanged = { created: Array<string>, modified: Array<string>, deleted: Array<string>, diffs: Array<FileDiff>, };
