// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalResponse } from "./ApprovalResponse";
import type { GenerationRequest } from "./GenerationRequest";
import type { ToolApprovalResponse } from "./ToolApprovalResponse";
import type { UserMessage } from "./UserMessage";

/**
 * Top-level inbound message envelope.
 */
export type InboundMessage = { "type": "user_message" } & UserMessage | { "type": "cancel" } | { "type": "approval_response" } & ApprovalResponse | { "type": "tool_approval_response" } & ToolApprovalResponse | { "type": "generation_request" } & GenerationRequest;
