// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Definition for an installed tool, sent over the wire on
 * [`crate::AgentCapabilities`].
 *
 * Wire-compatible with `aura_core::InstalledToolDefinition` but
 * self-contained so this crate has no dependency on `aura-core`.
 */
export type InstalledToolIntegrationRequirement = { integration_id: string | null, provider: string | null, kind: string | null, };
