// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Definition for an installed integration, sent over the wire on
 * [`crate::AgentCapabilities`].
 */
export type InstalledIntegration = { integration_id: string, name: string, provider: string, kind: string, metadata: { [key in string]?: JsonValue }, };
