// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A user-supplied attachment (image or text file) sent with a
 * message.
 */
export type MessageAttachment = { 
/**
 * `"image"` or `"text"`.
 */
type: string, 
/**
 * MIME type (e.g. `"image/png"`).
 */
media_type: string, 
/**
 * Base64-encoded payload.
 */
data: string, 
/**
 * Optional filename.
 */
name: string | null, 
/**
 * URL to fetch content from (e.g. S3).
 */
source_url: string | null, };
