// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningEffort } from "./ReasoningEffort";
import type { SessionModelOverrides } from "./SessionModelOverrides";

/**
 * "What model to drive the agent with."
 */
export type ModelSelection = { 
/**
 * Model identifier (e.g. `"claude-opus-4-7"`).
 */
id: string | null, 
/**
 * Maximum tokens per model response.
 */
max_tokens: number | null, 
/**
 * Maximum agentic steps per turn.
 */
max_turns: number | null, 
/**
 * Sampling temperature.
 */
temperature: number | null, 
/**
 * User-selected reasoning-effort tier from the chat model picker's
 * thinking-level flyout. The harness maps this into its
 * `ThinkingEffort` enum and hard-pins it across the turn. Absent
 * for models without effort tiers and for older clients.
 */
reasoning_effort: ReasoningEffort | null, 
/**
 * Optional per-session model overrides applied on top of the
 * harness's env-default router config.
 */
provider_overrides: SessionModelOverrides | null, };
