// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for `progress` heartbeat / status events.
 *
 * `stage` is the only required field and carries a free-form short
 * label (`"tool_running"`, `"lagged"`, `"forked_for_context"`, …).
 * Unknown stages flow straight through to the client which renders
 * them as a generic progress label, so we can introduce new stages
 * without coordinating a wire bump.
 *
 * Optional fields are omitted from the JSON when `None`
 * (`skip_serializing_if = "Option::is_none"`) and default to `None`
 * inbound (`#[serde(default)]`) so older harness/client pairs that
 * don't know about them deserialize cleanly.
 */
export type ProgressMsg = { 
/**
 * Short machine-readable stage tag. The aura-os chat client
 * renders unknown values as the literal label, so adding new
 * stages does not require a coordinated client release.
 */
stage: string, 
/**
 * Tool whose long-running execution is producing this heartbeat.
 * Set on `stage = "tool_running"`; left `None` for stages that
 * don't refer to a single tool (e.g. `"lagged"`).
 */
tool_name: string | null, 
/**
 * Wall-clock milliseconds since the heartbeat's reference event
 * (tool start for `"tool_running"`). Optional — older clients
 * ignore it.
 */
elapsed_ms: bigint | null, 
/**
 * Optional human-readable label / detail string.
 */
message: string | null, };
