// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatProjectInfoWire } from "./ChatProjectInfoWire";

/**
 * "Which project + which billing partition."
 *
 * `None` on a [`RuntimeRequest`] means "no project" (ad-hoc chat).
 */
export type ProjectContext = { 
/**
 * Project UUID for domain tool calls (specs, tasks, etc.).
 */
project_id: string, 
/**
 * Typed project descriptor surfaced into the chat-path system
 * prompt's `<project_context>` section.
 */
project_info: ChatProjectInfoWire | null, 
/**
 * Organization UUID for `X-Aura-Org-Id` billing header.
 */
aura_org_id: string | null, 
/**
 * Storage session UUID for `X-Aura-Session-Id` billing header.
 */
aura_session_id: string | null, 
/**
 * Project-agent UUID for `X-Aura-Agent-Id` billing header.
 */
aura_agent_id: string | null, };
