// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User-selected reasoning-effort tier carried end-to-end from the chat
 * model picker to the router.
 *
 * Provider-accurate **superset** — each model only exposes the subset
 * it supports (gated in the aura-os model catalog). `Minimal` is
 * OpenAI's lowest `reasoning_effort` tier; `Max` is Anthropic's largest
 * thinking budget (OpenAI has no `max`, so the router clamps it to
 * `high`). The harness maps these onto its internal Anthropic budget
 * tiers and the router translates them into each provider's native
 * control.
 */
export type ReasoningEffort = "minimal" | "low" | "medium" | "high" | "max";
