// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentCapabilities } from "./AgentCapabilities";
import type { AgentIdentity } from "./AgentIdentity";
import type { AgentPermissionsWire } from "./AgentPermissionsWire";
import type { AgentToolPermissionsWire } from "./AgentToolPermissionsWire";
import type { ModelSelection } from "./ModelSelection";
import type { ProjectContext } from "./ProjectContext";
import type { RuntimeRequestType } from "./RuntimeRequestType";
import type { WorkspaceLocation } from "./WorkspaceLocation";

/**
 * Canonical body of `POST /v1/run`.
 *
 * Returned synchronously with `{ run_id, event_stream_url }`. The
 * caller then opens `WS /stream/:run_id` to receive events (and, on
 * the [`RuntimeRequestType::Chat`] variant, to send `user_message`
 * frames).
 */
export type RuntimeRequest = { 
/**
 * Discriminated union carrying the data unique to each request
 * type. Renamed `r#type` so the wire payload uses the natural
 * `"type"` key while Rust still gets a typed enum match.
 */
type: RuntimeRequestType, 
/**
 * Who is this agent — template + partition + persona + skills +
 * system prompt. See [`AgentIdentity`].
 */
agent_identity: AgentIdentity, 
/**
 * What model to drive the agent with: id, max_tokens, max_turns,
 * temperature, provider_overrides.
 */
model: ModelSelection, 
/**
 * Where the agent runs: workspace path, project path, git
 * repo/branch.
 */
workspace: WorkspaceLocation, 
/**
 * Project context: project_id, typed project_info, billing
 * header values (`aura_org_id`, `aura_session_id`,
 * `aura_agent_id`). `None` only for callers that have no project
 * (e.g. ad-hoc chat).
 */
project: ProjectContext | null, 
/**
 * Policy bundle — what the agent is **allowed** to do.
 * Capability + scope grants enforced by the kernel policy gate.
 */
agent_permissions: AgentPermissionsWire, 
/**
 * Per-tool on/off overrides layered on top of
 * [`Self::agent_permissions`].
 */
tool_permissions: AgentToolPermissionsWire | null, 
/**
 * Runtime tools / integrations / intent classifier the agent
 * **can use**.
 */
agent_capabilities: AgentCapabilities, 
/**
 * Bearer JWT forwarded to the model proxy + domain API calls.
 * `None` is valid in dev (auth disabled).
 */
auth_jwt: string | null, 
/**
 * Originating end-user id for resolving + persisting tool
 * defaults.
 */
user_id: string, };
