// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response body of `POST /v1/run`.
 */
export type RuntimeRunResponse = { 
/**
 * Stable identifier for the spawned run.
 */
run_id: string, 
/**
 * Convenience field — the relative WS path the client should
 * open. Always `/stream/:run_id`.
 */
event_stream_url: string, };
