// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationMessage } from "./ConversationMessage";
import type { CouncilMechanism } from "./CouncilMechanism";
import type { CouncilMember } from "./CouncilMember";

/**
 * Discriminated union carrying the data unique to each run type.
 */
export type RuntimeRequestType = { "kind": "chat", "params": { 
/**
 * Prior conversation messages to hydrate into session
 * history (empty for a brand-new session).
 */
conversation_messages: Array<ConversationMessage>, } } | { "kind": "dev_loop", "params": Record<string, never> } | { "kind": "task_run", "params": { 
/**
 * Task UUID the automaton should execute.
 */
task_id: string, 
/**
 * Retry warm-up: the reason text persisted on the previous
 * attempt's `task_failed` record.
 */
prior_failure: string | null, 
/**
 * Retry warm-up: recent work-log entries the agent should
 * re-see.
 */
work_log: Array<string>, } } | { "kind": "council", "params": { 
/**
 * Council member models in order; `members[0]` synthesizes.
 */
members: Array<CouncilMember>, 
/**
 * How `members[0]` combines the members' answers once every
 * member has completed. Defaults to [`CouncilMechanism::Synthesize`]
 * for older clients that omit the field.
 */
mechanism: CouncilMechanism, 
/**
 * Prior conversation messages to hydrate into session history.
 */
conversation_messages: Array<ConversationMessage>, } };
