// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextBreakdown } from "./ContextBreakdown";

/**
 * Token usage information for a session.
 */
export type SessionUsage = { input_tokens: bigint, output_tokens: bigint, estimated_context_tokens: bigint, cache_creation_input_tokens: bigint, cache_read_input_tokens: bigint, cumulative_input_tokens: bigint, cumulative_output_tokens: bigint, cumulative_cache_creation_input_tokens: bigint, cumulative_cache_read_input_tokens: bigint, 
/**
 * Fraction of the model's context window consumed (0.0–1.0).
 */
context_utilization: number, 
/**
 * Model identifier used for this turn.
 */
model: string, 
/**
 * Provider name (e.g., "anthropic").
 */
provider: string, 
/**
 * Per-bucket token estimates that sum (approximately) to
 * `estimated_context_tokens`. Strictly additive — older harness
 * builds emit `ContextBreakdown::default()` (all zeros), and the
 * frontend treats an all-zero breakdown as "not available" and
 * falls back to the legacy used/total view.
 */
context_breakdown: ContextBreakdown, };
