// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-session model overrides applied on top of the harness's
 * env-default router config.
 */
export type SessionModelOverrides = { 
/**
 * Optional default model for this session.
 */
default_model: string | null, 
/**
 * Optional fallback model used on 429/529 retries.
 */
fallback_model: string | null, 
/**
 * Optional override for whether Anthropic prompt-caching
 * directives should be attached.
 */
prompt_caching_enabled: boolean | null, 
/**
 * Optional stable cache key forwarded to aura-router for
 * OpenAI-family prompt caching.
 */
prompt_cache_key: string | null, 
/**
 * Optional retention hint paired with [`Self::prompt_cache_key`].
 */
prompt_cache_retention: string | null, };
