// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentPermissionsWire } from "./AgentPermissionsWire";
import type { AgentToolPermissionsWire } from "./AgentToolPermissionsWire";
import type { ConversationMessage } from "./ConversationMessage";
import type { InstalledIntegration } from "./InstalledIntegration";
import type { InstalledTool } from "./InstalledTool";
import type { IntentClassifierSpec } from "./IntentClassifierSpec";
import type { SessionModelOverrides } from "./SessionModelOverrides";

/**
 * Payload for `session_init`.
 */
export type SessionInit = { system_prompt: string | null, 
/**
 * Model identifier (e.g., "claude-opus-4-6").
 */
model: string | null, 
/**
 * Maximum tokens per model response.
 */
max_tokens: number | null, 
/**
 * Sampling temperature.
 */
temperature: number | null, 
/**
 * Maximum agentic steps per turn.
 */
max_turns: number | null, 
/**
 * Installed tools to register for this session.
 */
installed_tools: Array<InstalledTool> | null, 
/**
 * Installed integrations authorized for this session.
 */
installed_integrations: Array<InstalledIntegration> | null, 
/**
 * Workspace directory path (must be under the server's workspace base).
 */
workspace: string | null, 
/**
 * Absolute path to the real project directory on the host filesystem.
 * When set, tool execution happens directly in this directory instead of
 * the sandboxed `aura_data/workspaces/` tree.
 */
project_path: string | null, 
/**
 * JWT auth token for proxy routing.
 */
token: string | null, 
/**
 * Project ID for domain tool calls (specs, tasks, etc.).
 */
project_id: string | null, 
/**
 * Prior conversation messages to restore into session history.
 */
conversation_messages: Array<ConversationMessage> | null, 
/**
 * Project-agent UUID for X-Aura-Agent-Id billing header.
 */
aura_agent_id: string | null, 
/**
 * Storage session UUID for X-Aura-Session-Id billing header.
 */
aura_session_id: string | null, 
/**
 * Organization UUID for X-Aura-Org-Id billing header.
 */
aura_org_id: string | null, 
/**
 * Harness-level agent ID for per-agent skill lookup.
 * Set by the caller (e.g. aura-os) so the harness can resolve which
 * skills are installed for this agent.
 */
agent_id: string | null, 
/**
 * Template agent id for skill / permissions / billing lookup.
 *
 * `agent_id` (above) is the partition key the harness uses for
 * turn-locking, derived from the AgentInstance via
 * `aura_os_core::harness_agent_id`. `template_agent_id` is the
 * stable Aura template id (the row in `agents`) so the harness
 * can resolve installed skills, agent-level permissions, and
 * billing aggregation against a single identity per template
 * even when multiple partitions exist.
 *
 * Optional: when `None`, the harness falls back to `agent_id`
 * for skill lookup.
 */
template_agent_id: string | null, 
/**
 * Originating end-user id for resolving and persisting tool defaults.
 */
user_id: string, 
/**
 * Optional per-session model overrides applied on top of the
 * harness's env-default router config. `None` means "use the
 * harness's defaults verbatim".
 */
provider_overrides: SessionModelOverrides | null, 
/**
 * Optional keyword-driven intent classifier spec. When present the harness
 * narrows the per-turn tool surface based on each user message using the
 * same tier-1 / tier-2 domain rules aura-os used to run in-process for
 * the CEO-preset agent. Ships as the profile-JSON subset that
 * `aura-tools::IntentClassifier::from_profile_json` accepts, plus a
 * `tool_domains` map from tool name to domain so the harness can narrow
 * `tool_definitions` (which are opaque to the classifier otherwise).
 */
intent_classifier: IntentClassifierSpec | null, 
/**
 * Explicit [`AgentPermissionsWire`] bundle for this session. Required
 * on every session; the harness enforces scope + capability checks
 * unconditionally against these grants. See the module-level
 * "Agent permissions model" section for details.
 */
agent_permissions: AgentPermissionsWire, 
/**
 * Optional per-agent tool override stamped onto this session. `None`
 * means the harness should load the persisted agent override, if any;
 * an empty map means "explicitly inherit the user default".
 */
tool_permissions: AgentToolPermissionsWire | null, };
