// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for `subagent_status`.
 *
 * `state` is one of `running | completed | failed | cancelled |
 * timeout | rejected`. `reason` carries the failure/rejection detail
 * when applicable (depth/quota rejections surface here).
 */
export type SubagentStatus = { child_run_id: string, state: string, reason: string | null, };
