// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for `subagent_spawned`.
 *
 * Announces a child subagent run on the parent stream. `child_run_id`
 * is a freshly minted run id the client can attach to via
 * `WS /stream/:child_run_id`. `parent_tool_use_id` ties the thread
 * back to the originating `task` tool-use block so the UI can render
 * the live thread under that tool card.
 */
export type SubagentSpawned = { child_run_id: string, parent_tool_use_id: string | null, subagent_type: string, prompt: string, 
/**
 * Model id driving this child run. Set for AURA Council members so
 * the UI can label each column; `None` for ordinary `task` spawns.
 */
model: string | null, 
/**
 * Zero-based council slot index for AURA Council members (ordering
 * the columns); `None` for ordinary `task` spawns.
 */
council_index: number | null, 
/**
 * Council combine mechanism (`synthesize` / `contrast` /
 * `side_by_side`) shared by every member of the turn. Set on AURA
 * Council member spawns so the UI can label the panel with the
 * active mechanism; `None` for ordinary `task` spawns.
 */
council_mechanism: string | null, };
