// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageAttachment } from "./MessageAttachment";

/**
 * Payload for `user_message`.
 */
export type UserMessage = { content: string, 
/**
 * Optional list of tool names the user wants prioritized for
 * this message.
 */
tool_hints: Array<string> | null, 
/**
 * Optional image/text attachments (base64-encoded).
 */
attachments: Array<MessageAttachment> | null, };
