/**
 * Curated subset of Lucide icon names shown by default in the project
 * icon picker. Hand-picked to lean toward shapes that read clearly as
 * "project identity" at small sizes — animals, objects, abstract
 * symbols, common tools. The full Lucide library (~1500 icons) is
 * still searchable via the picker's search input; this is just the
 * "first impression" surface that loads instantly.
 *
 * Names are kebab-case as expected by `lucide-react/dynamic`'s
 * `DynamicIcon` component.
 */
export const APPEARANCE_ICON_PRESETS: readonly string[] = [
  // Tech & code
  "rocket",
  "code",
  "code-2",
  "terminal",
  "cpu",
  "database",
  "server",
  "cloud",
  "bug",
  "wrench",
  "cog",
  "hammer",
  // Containers & structures
  "folder",
  "folder-open",
  "box",
  "boxes",
  "package",
  "archive",
  "briefcase",
  "building",
  "warehouse",
  // Symbols & shapes
  "star",
  "heart",
  "flame",
  "zap",
  "circle",
  "square",
  "triangle",
  "diamond",
  "hexagon",
  "octagon",
  "shield",
  "shield-check",
  "crown",
  "trophy",
  "award",
  "gem",
  "sparkles",
  "wand",
  // Communication
  "message-circle",
  "message-square",
  "mail",
  "send",
  "megaphone",
  "bell",
  // Productivity
  "calendar",
  "clock",
  "list-checks",
  "list-todo",
  "clipboard",
  "clipboard-list",
  "notebook",
  "book",
  "book-open",
  "bookmark",
  "file-text",
  "files",
  "pencil",
  "edit-3",
  "highlighter",
  // Tools
  "settings",
  "sliders-horizontal",
  "key",
  "lock",
  "unlock",
  "search",
  "filter",
  "scissors",
  "ruler",
  "compass",
  "map",
  "map-pin",
  "navigation",
  "globe",
  // Life & nature
  "sun",
  "moon",
  "cloud-rain",
  "snowflake",
  "leaf",
  "tree-pine",
  "sprout",
  "flower",
  // Animals
  "cat",
  "dog",
  "bird",
  "fish",
  "rabbit",
  "squirrel",
  // Food & objects
  "coffee",
  "cookie",
  "pizza",
  "ice-cream",
  "cake",
  "music",
  "headphones",
  "camera",
  "image",
  "film",
  "gamepad-2",
  "puzzle",
  "dice-6",
  // Vehicles
  "car",
  "bike",
  "plane",
  "ship",
  "train-front",
  // Misc
  "atom",
  "telescope",
  "microscope",
  "flask-conical",
  "test-tube",
  "graduation-cap",
  "lightbulb",
  "brain",
  "infinity",
  "anchor",
  "feather",
  "footprints",
  "fingerprint",
  "ghost",
  "skull",
  "smile",
  "eye",
  "thumbs-up",
];
